# Generated by Django 3.1.6 on 2021-02-21 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("User", "유저"),
                            ("Worldcup", "월드컵"),
                            ("Media", "미디어"),
                            ("Comment", "댓글"),
                        ],
                        max_length=10,
                        verbose_name="신고 대상 유형",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="신고 대상 id")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Adult", "성적 요소"),
                            ("Hate", "혐오"),
                            ("Spam", "스팸 및 광고"),
                            ("Child Abuse", "아동학대"),
                            ("Other", "기타"),
                        ],
                        max_length=16,
                        verbose_name="신고 사유",
                    ),
                ),
                ("report", models.CharField(max_length=511, verbose_name="신고 내용")),
                (
                    "image",
                    models.ImageField(
                        upload_to="reportapp/report/%Y/%m/%d", verbose_name="증빙 사진"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "unique_together": {("target_type", "target_id")},
            },
        ),
    ]
