# Generated by Django 3.1.6 on 2021-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="reportapp/report/%Y/%m/%d", verbose_name="증빙 사진"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report",
            field=models.CharField(blank=True, max_length=511, verbose_name="신고 내용"),
        ),
    ]
