# Generated by Django 3.1.6 on 2021-03-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="처리 여부"),
        ),
    ]
