# Generated by Django 3.1.6 on 2021-03-02 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reportapp", "0002_auto_20210224_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="작성일"
            ),
            preserve_default=False,
        ),
    ]
