# Generated by Django 3.1.6 on 2021-03-04 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worldcupapp", "0004_auto_20210303_0808"),
        ("reportapp", "0003_report_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "성적 요소가 포함되어 있습니다."),
                            (2, "증오/혐오 등의 내용이 포함되어 있습니다."),
                            (3, "스팸 및 광고성 내용이 포함되어 있습니다."),
                            (4, "아동학대 관련 내용이 포함되어 있습니다."),
                            (5, "기타"),
                        ],
                        verbose_name="신고 사유",
                    ),
                ),
                (
                    "body",
                    models.CharField(blank=True, max_length=511, verbose_name="신고 내용"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="reportapp/report/%Y/%m/%d",
                        verbose_name="증빙 사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.comment",
                        verbose_name="댓글",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "성적 요소가 포함되어 있습니다."),
                            (2, "증오/혐오 등의 내용이 포함되어 있습니다."),
                            (3, "스팸 및 광고성 내용이 포함되어 있습니다."),
                            (4, "아동학대 관련 내용이 포함되어 있습니다."),
                            (5, "기타"),
                        ],
                        verbose_name="신고 사유",
                    ),
                ),
                (
                    "body",
                    models.CharField(blank=True, max_length=511, verbose_name="신고 내용"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="reportapp/report/%Y/%m/%d",
                        verbose_name="증빙 사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.basemedia",
                        verbose_name="미디어",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "성적 요소가 포함되어 있습니다."),
                            (2, "증오/혐오 등의 내용이 포함되어 있습니다."),
                            (3, "스팸 및 광고성 내용이 포함되어 있습니다."),
                            (4, "아동학대 관련 내용이 포함되어 있습니다."),
                            (5, "기타"),
                        ],
                        verbose_name="신고 사유",
                    ),
                ),
                (
                    "body",
                    models.CharField(blank=True, max_length=511, verbose_name="신고 내용"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="reportapp/report/%Y/%m/%d",
                        verbose_name="증빙 사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorldcupReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "성적 요소가 포함되어 있습니다."),
                            (2, "증오/혐오 등의 내용이 포함되어 있습니다."),
                            (3, "스팸 및 광고성 내용이 포함되어 있습니다."),
                            (4, "아동학대 관련 내용이 포함되어 있습니다."),
                            (5, "기타"),
                        ],
                        verbose_name="신고 사유",
                    ),
                ),
                (
                    "body",
                    models.CharField(blank=True, max_length=511, verbose_name="신고 내용"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="reportapp/report/%Y/%m/%d",
                        verbose_name="증빙 사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.worldcup",
                        verbose_name="월드컵",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
