# Generated by Django 3.1.6 on 2021-03-08 09:59

import accountapp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0003_auto_20210301_0605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                error_messages={"max_length": "최대 20글자 까지 입력할 수 있습니다."},
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(8, "최소 8글자 이상 입력해주세요.")
                ],
                verbose_name="PW",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"max_length": "최대 15글자 까지 입력할 수 있습니다."},
                max_length=15,
                unique=True,
                validators=[
                    accountapp.validators.CustomASCIIUsernameValidator(),
                    django.core.validators.MinLengthValidator(5, "최소 5글자 이상 입력해주세요."),
                ],
                verbose_name="ID",
            ),
        ),
    ]
