# Generated by Django 3.1.6 on 2021-03-08 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0004_auto_20210308_0959"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.MinLengthValidator(8, "최소 8글자 이상 입력해주세요."),
                    django.core.validators.MaxLengthValidator(
                        20, "최대 20글자 까지 입력할 수 있습니다."
                    ),
                ],
                verbose_name="PW",
            ),
        ),
    ]
