# Generated by Django 3.1.6 on 2021-03-12 07:16

import accountapp.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_auto_20210309_0946'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accountapp.models.user.CustomUserManager()),
            ],
        ),
    ]
