# Generated by Django 3.1.6 on 2021-03-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0007_auto_20210308_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                editable=False, max_length=254, unique=True, verbose_name="이메일"
            ),
        ),
    ]
