# Generated by Django 3.1.6 on 2021-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0008_auto_20210312_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
