version: '3.1'

services:

  database:
    # https://hub.docker.com/_/postgres
    image: postgres:9.6.21
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      # if no write, ==POSTGRES_USER
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  app-server:
    build:
      # build path 변경
      context: ..
      # Dockerfile의 경로
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - database
    volumes:
      - ..:/app
    working_dir: /app
    environment: 
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

volumes:
  database_volume: