# Development
FROM python:3.9

# .pyc 파일 생성 안함
ENV PYTHONDONTWRITEBYTECODE 1
# std 버퍼 제거
ENV PYTHONUNBUFFERED 1

# build 시 context dir이 docker deamon으로 이동된다.
# 그러므로 ../ 등의 상위 경로를 사용할 수 없다.
# compose에 의해 사용되므로, project path에 Dockerfile이 있다는 가정하에 경로를 설정
ADD requirements/common.txt requirements/dev.txt /app/requirements/

WORKDIR /app

RUN pip install -r requirements/dev.txt