# Production

# https://hub.docker.com/_/python
FROM python:3.9

# .pyc 파일 생성 안함
ENV PYTHONDONTWRITEBYTECODE 1
# std 버퍼 제거
ENV PYTHONUNBUFFERED 1

ADD requirements/common.txt requirements/prod.txt /app/requirements/

WORKDIR /app

RUN pip install -r requirements/prod.txt

ADD . .