version: '3'

services:

  database:
    # https://hub.docker.com/_/postgres
    image: postgres:9.6.21
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    networks:
      - backend

  app-server:
    build:
      # build 기준 경로 변경
      context: ..
      # 변경된 경로를 기준으로 Dockerfile의 상대경로 지정
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - database
    networks: 
      - frontend
      - backend
    volumes:
      - ..:/app
    working_dir: /app
    environment: 
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

volumes:
  database_volume:

networks:
  frontend:
  backend: