# Generated by Django 3.1.6 on 2021-02-19 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GifMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="제목")),
                (
                    "win_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="승리 횟수"
                    ),
                ),
                (
                    "choice_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="1:1 선택 횟수"
                    ),
                ),
                (
                    "media",
                    models.ImageField(
                        upload_to="worldcupapp/imagemedia/%Y/%m/%d/%H",
                        verbose_name="Gif 미디어",
                    ),
                ),
            ],
            options={
                "db_table": "Medias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="제목")),
                (
                    "win_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="승리 횟수"
                    ),
                ),
                (
                    "choice_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="1:1 선택 횟수"
                    ),
                ),
                (
                    "media",
                    models.ImageField(
                        upload_to="worldcupapp/imagemedia/%Y/%m/%d/%H",
                        verbose_name="Image 미디어",
                    ),
                ),
            ],
            options={
                "db_table": "Medias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TextMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="제목")),
                (
                    "win_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="승리 횟수"
                    ),
                ),
                (
                    "choice_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="1:1 선택 횟수"
                    ),
                ),
                ("media", models.CharField(max_length=511, verbose_name="Text 미디어")),
            ],
            options={
                "db_table": "Medias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VideoMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="제목")),
                (
                    "win_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="승리 횟수"
                    ),
                ),
                (
                    "choice_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="1:1 선택 횟수"
                    ),
                ),
                ("media", models.CharField(max_length=255, verbose_name="텍스트 미디어")),
            ],
            options={
                "db_table": "Medias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BaseMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="제목")),
                ("media", models.CharField(max_length=511, verbose_name="미디어")),
                (
                    "win_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="승리 횟수"
                    ),
                ),
                (
                    "choice_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="1:1 선택 횟수"
                    ),
                ),
            ],
            options={
                "db_table": "Medias",
            },
        ),
        migrations.CreateModel(
            name="Worldcup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "열 글자 이상 입력해주세요."
                            )
                        ],
                        verbose_name="제목",
                    ),
                ),
                ("subtitle", models.CharField(max_length=511, verbose_name="부제")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("T", "Text"),
                            ("I", "Image"),
                            ("G", "Gif"),
                            ("V", "Image"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="미디어 타입",
                    ),
                ),
                (
                    "publish_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "공개"),
                            ("PRIVATE", "비공개"),
                            ("PASSWORD", "암호"),
                        ],
                        max_length=8,
                        verbose_name="배포 방식",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "여덟 글자 이상 입력해주세요."
                            )
                        ],
                        verbose_name="암호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "play_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="플레이 완료 횟수"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=511, verbose_name="댓글 내용")),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.basemedia",
                        verbose_name="미디어",
                    ),
                ),
                (
                    "worldcup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.worldcup",
                        verbose_name="월드컵",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basemedia",
            name="worldcup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="worldcupapp.worldcup",
                verbose_name="월드컵",
            ),
        ),
    ]
