# Generated by Django 3.1.6 on 2021-03-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worldcupapp", "0003_auto_20210225_0945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemedia",
            name="worldcup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_set",
                to="worldcupapp.worldcup",
                verbose_name="월드컵",
            ),
        ),
    ]
