# Generated by Django 3.1.6 on 2021-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcupapp", "0008_auto_20210305_0646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="anonymous_nickname",
            field=models.CharField(default="익명", max_length=13, verbose_name="익명 닉네임"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="anonymous_password",
            field=models.CharField(max_length=15, verbose_name="익명 패스워드"),
        ),
    ]
