# Generated by Django 3.1.6 on 2021-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldcupapp", "0009_auto_20210306_0754"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basemedia",
            old_name="media",
            new_name="body",
        ),
        migrations.AlterField(
            model_name="worldcup",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Text", "텍스트"),
                    ("Image", "이미지"),
                    ("Gif", "움짤"),
                    ("Video", "외부 비디오 링크"),
                ],
                default="Image",
                max_length=15,
                verbose_name="미디어 타입",
            ),
        ),
    ]
