# Generated by Django 3.1.6 on 2021-03-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0010_auto_20210310_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemedia',
            name='worldcup',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='worldcup',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.DeleteModel(
            name='GifMedia',
        ),
        migrations.DeleteModel(
            name='ImageMedia',
        ),
        migrations.DeleteModel(
            name='TextMedia',
        ),
        migrations.DeleteModel(
            name='VideoMedia',
        ),
        migrations.DeleteModel(
            name='BaseMedia',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
