# Generated by Django 3.1.6 on 2021-03-22 07:27

import accountapp.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("worldcupapp", "0013_gifmedia_imagemedia_media_textmedia_videomedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=511, verbose_name="댓글 내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시각"),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.media",
                        verbose_name="미디어",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_worldcupapp.comment_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "worldcup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worldcupapp.worldcup",
                        verbose_name="월드컵",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AnonUserComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldcupapp.comment",
                    ),
                ),
                (
                    "anon_nickname",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "세 글자 이상 입력해주세요."
                            ),
                            accountapp.validators.CustomUnicodeNicknameValidator(),
                            django.core.validators.MaxLengthValidator(13),
                        ],
                        verbose_name="익명 닉네임",
                    ),
                ),
                (
                    "anon_password",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                8, "최소 8글자 이상 입력해주세요."
                            ),
                            django.core.validators.MaxLengthValidator(
                                20, "최대 20글자 까지 입력할 수 있습니다."
                            ),
                            django.core.validators.MaxLengthValidator(128),
                        ],
                        verbose_name="익명 패스워드",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("worldcupapp.comment",),
        ),
        migrations.CreateModel(
            name="AuthUserComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="worldcupapp.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("worldcupapp.comment",),
        ),
    ]
