# Generated by Django 3.1.6 on 2021-03-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worldcupapp", "0015_auto_20210322_0745"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authusercomment",
            old_name="user",
            new_name="writer",
        ),
    ]
