# Generated by Django 3.1.6 on 2021-03-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worldcupapp", "0016_auto_20210322_0750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gifmedia",
            name="media_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
        migrations.AlterField(
            model_name="imagemedia",
            name="media_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
        migrations.AlterField(
            model_name="textmedia",
            name="media_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
        migrations.AlterField(
            model_name="videomedia",
            name="media_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
    ]
