# Generated by Django 3.1.6 on 2021-03-27 06:43

from django.db import migrations, models
import django.db.models.deletion
import worldcupapp.models.media


class Migration(migrations.Migration):

    dependencies = [
        ("worldcupapp", "0019_auto_20210327_0633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gifmedia",
            name="media_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
        migrations.AlterField(
            model_name="imagemedia",
            name="media_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="worldcup",
            field=models.ForeignKey(
                on_delete=worldcupapp.models.media.NON_POLYMORPHIC_CASCADE,
                related_name="media_set",
                to="worldcupapp.worldcup",
                verbose_name="월드컵",
            ),
        ),
        migrations.AlterField(
            model_name="textmedia",
            name="media_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
        migrations.AlterField(
            model_name="videomedia",
            name="media_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="worldcupapp.media",
            ),
        ),
    ]
