name: testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run migrations
        run: python manage.py --settings=backend.settings.action migrate
      - name: Run tests
        run: python manage.py --settings=backend.settings.action test